name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Package Application
        run: |
          zip -r deploy.zip . -x "*.git*"

      - name: Upload to S3
        run: |
          aws s3 cp deploy.zip s3://shahid-demo-deploy-bucket/deploy.zip

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name shahid-demo --version-label $GITHUB_SHA --source-bundle S3Bucket=shahid-demo-deploy-bucket,S3Key=deploy.zip
          aws elasticbeanstalk update-environment --application-name shahid-demo --environment-name Shahid-demo-env --version-label $GITHUB_SHA
